### PR TITLE
update readme to add free

### PR DESCRIPTION
**Pull request by mohamedGamalAbuGalala**

### CODE REVIEW

**Comment by Lakr233** [comment]
😅

**Comment by mohamedGamalAbuGalala** [comment]
> 😅

I mistakenly created the PR on your repository (I intended to create it on my fork but overlooked the destination). However, I forked your repo and added the release 😂, in case anyone wants to use it.

**Comment by Lakr233** [comment]
😂 Actually you can find this app on some one's HomeBrew.

**Comment by mohamedGamalAbuGalala** [comment]
> 😂 Actually you can find this app on some one's HomeBrew.

That's a fun story to tell, my cousin is not a tech person and found your repo and wanted to do the release by himself using ChatGPT, but he couldn't and asked me to help and I did without even searching anywhere.
I'm a web dev and have zero experience with building Swift apps, but it was super easy with https://www.cursor.com

**Comment by mohamedGamalAbuGalala** [comment]
We can code Rockets OS now using AI 🤖 😂

**Pull request closed without merging**
